server:
  port: 9000
spring:
  application:
    name: "cards"
  profiles:
    active: "qa"
  datasource:
    url: jdbc:mysql://localhost:3309/cardsdb
    username: root
    password: root2
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  config:
    import: "configserver:http://localhost:8071/"
  cloud:
    config:
      uri: "http://configserver:8071/"

management:
  endpoints:
    web:
      exposure:
        include: "*"
