services:
  accounts:
    image: "rajadocker9971/accounts:v1"
    container_name: accounts-ms
    ports:
      - "8089:8089"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - bank-network
  loans:
    image: "rajadocker9971/loans:v1"
    container_name: loans-ms
    ports:
      - "8099:8099"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - bank-network
  cards:
    image: "rajadocker9971/cards:v1"
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - bank-network
networks:
  bank-network:
    driver: "bridge"