spring:
  application:
    name: "gatewayserver"
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    config:
      uri: "http://configserver:8071/"
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceIds: true


management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: "/actuator"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    gateway:
      enabled: true
    health:
      show-details: ALWAYS
      probes:
        add-additional-paths: true
        enabled: true
info:
  description: "gatewayserver"
  version: "1.0.0"
  title: "Bank Gateway Server Microservice"

logging:
  level:
    com:
      raja:
        gatewayserver: DEBUG