spring:
  application:
    name: "gatewayserver"
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: "/actuator"
  info:
    env:
      enabled: true
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    gateway:
      enabled: true
    health:
      show-details: ALWAYS
      probes:
        add-additional-paths: true
        enabled: true
    shutdown:
      enabled: true

info:
  description: "Bank Gateway Server Application"
  version: "1.0.0"
  title: "Gateway Server"



