server:
  port: 8099
spring:
  application:
    name: "loans"
  profiles:
    active: "qa"
  datasource:
    url: jdbc:mysql://localhost:3308/loansdb
    username: root
    password: root2
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  config:
    import: "configserver:http://127.0.0.1:8071/"
management:
  endpoints:
    web:
      exposure:
        include: "*"