server:
  port: 8099
info:
  description: "Loans Microservice"
  version: "1.0.0"
  title: "Loans Microservice"
spring:
  application:
    name: "loans"
  profiles:
    active: "qa"
  datasource:
    url: jdbc:mysql://localhost:3308/loansdb
    username: root
    password: root2
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    config:
      uri: "http://configserver:8071/"
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: "/actuator"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      show-details: ALWAYS
      probes:
        add-additional-paths: true
        enabled: true
    shutdown:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}


eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
