build:
  version: "3.0"

accounts:
  message: "Welcome to Bank accounts related local(V2) APIs "
  contactDetails:
    name: "John Doe - Developer"
    email: "john@eazybank.com"
  onCallSupport:
    - (555) 555-1234
