build:
  version: "1.0"

accounts:
  message: "Welcome to EazyBank accounts related prod APIs "
  contactDetails:
    name: "Reine Aishwarya - Product Owner"
    email: "{cipher}329e62c5c33dc71577b7d6106e6a8d84a9937a85ec252af9a337a4f7a2cfc068ea9f4618b019559af293ad80330bbad7"
  onCallSupport:
    - (453) 392-4829
    - (236) 203-0384