server:
  port: 8089
spring:
  application:
    name: "accounts"
  profiles:
    active: "qa"
  datasource:
    url: jdbc:mysql://localhost:3307/accountsdb
    username: root
    password: root2
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    config:
      uri: "http://configserver:8071/"

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: "/actuator"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      show-details: ALWAYS
      probes:
        add-additional-paths: true
        enabled: true
