services:
  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - eazybank
#    extends:
#      file: common-config.yml
#      service: network-deploy-service

  configserver:
    image: "rajadocker9971/configserver:v2"
    container_name: configserver-ms
    ports:
      - "8071:8071"
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq  # Add this line if not set in properties
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    healthcheck:
      test: "curl --fail --silent http://configserver-ms:8071/actuator/health/readiness | grep UP || exit 1"
      #test: ["CMD", "sh", "-c", "wget -qO- http://localhost:8071/actuator/health/readiness | grep UP || exit 1" ]
      interval: 15s
      timeout: 5s
      retries: 10
      start_period: 60s
    networks:
      - eazybank
    extends:
      file: common-config.yml
      service: microservice-base-config

  accounts:
    image: "rajadocker9971/accounts:v2"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    depends_on:
      configserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "accounts"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

    loans:
      image: "rajadocker9971/loans:v2"
      container_name: loans-ms
      ports:
        - "8090:8090"
      depends_on:
        configserver:
          condition: service_healthy
      environment:
        SPRING_APPLICATION_NAME: "loans"
      extends:
        file: common-config.yml
        service: microservice-configserver-config

    cards:
      image: "rajadocker9971/cards:v2"
      container_name: cards-ms
      ports:
        - "9000:9000"
      depends_on:
        configserver:
          condition: service_healthy
      environment:
        SPRING_APPLICATION_NAME: "cards"
      extends:
        file: common-config.yml
        service: microservice-configserver-config


networks:
  eazybank:
    driver: "bridge"