services:
  accountsdb:
    container_name: accountsdb
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: accountsdb
    extends:
      service: microservice-db-config
      file: common-config.yml

  loansdb:
    container_name: loansdb
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: loansdb
    extends:
      service: microservice-db-config
      file: common-config.yml

  cardsdb:
    container_name: cardsdb
    ports:
      - "3309:3306"
    environment:
      MYSQL_DATABASE: cardsdb
    extends:
      service: microservice-db-config
      file: common-config.yml

  configserver:
    image: "rajadocker9971/configserver:v3"
    container_name: configserver-ms
    ports:
      - "8071:8071"
    healthcheck:
      test: "curl --fail --silent http://localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s
    extends:
      service: microservice-base-config
      file: common-config.yml

  eurekaserver:
    image: "rajadocker9971/eurekaserver:v3"
    container_name: eurekaserver-ms
    ports:
      - "8070:8070"
    environment:
      SPRING_APPLICATION_NAME: "eurekaserver"
    healthcheck:
      test: "curl --fail --silent http://localhost:8070/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 60s
    extends:
      service: microservice-configserver-config
      file: common-config.yml

  accounts:
    image: "rajadocker9971/accounts:v3"
    container_name: accounts-ms
    ports:
      - "8089:8089"
    environment:
      SPRING_APPLICATION_NAME: "accounts"
      SPRING_DATASOURCE_URL: "jdbc:mysql://accountsdb:3306/accountsdb"
    healthcheck:
      test: "curl --fail --silent http://localhost:8089/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 60s
    extends:
      service: microservice-eureka-config
      file: common-config.yml

  loans:
    image: "rajadocker9971/loans:v3"
    container_name: loans-ms
    ports:
      - "8099:8099"
    environment:
      SPRING_APPLICATION_NAME: "loans"
      SPRING_DATASOURCE_URL: "jdbc:mysql://loansdb:3306/loansdb"
    healthcheck:
      test: "curl --fail --silent http://localhost:8099/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 60s
    extends:
      service: microservice-eureka-config
      file: common-config.yml

  cards:
    image: "rajadocker9971/cards:v3"
    container_name: cards-ms
    ports:
      - "9000:9000"
    environment:
      SPRING_APPLICATION_NAME: "cards"
      SPRING_DATASOURCE_URL: "jdbc:mysql://cardsdb:3306/cardsdb"
    healthcheck:
      test: "curl --fail --silent http://localhost:9000/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 60s
    extends:
      service: microservice-eureka-config
      file: common-config.yml

networks:
  rajabank:
    driver: "bridge"