services:
  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: network-deploy-service

  configserver:
    image: "rajadocker9971/configserver:v2"
    container_name: configserver-ms
    ports:
      - "8071:8071"
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq  # Add this line if not set in properties
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    healthcheck:
      test: "curl --fail --silent http://localhost:8071/actuator/health/readiness | grep UP || exit 1"
      #test: ["CMD", "sh", "-c", "wget -qO- http://localhost:8071/actuator/health/readiness | grep UP || exit 1" ]
      interval: 15s
      timeout: 5s
      retries: 10
      start_period: 60s
    extends:
      file: common-config.yml
      service: microservice-base-config



networks:
  eazybank:
    driver: "bridge"