spring:

  application:
    name: "configserver"
  profiles:
    # active: native
    active: git
  cloud:
    config:
      server:
        # native:
        # search-locations: "classpath:/config"
        # search-locations: "file:///Users//eazybytes//Documents//config"
        git:
          uri: "https://github.com/rajaneshgit/bank-microservices-new.git"
          search-paths: "configserver/src/main/resources/config"
          default-label: main
          timeout: 10
          clone-on-start: true
          force-pull: true
          username: rajaneshgit
          password: "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"

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: "/actuator"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      show-details: ALWAYS
      probes:
        add-additional-paths: true
        enabled: true
encrypt:
  key: "edg12345wd678a901g23f456A"

server:
  port: 8071


